[stage]
default = "<central-env-dir>/.env"
dev     = "<central-env-dir>/.env.development"
stg     = "<central-env-dir>/.env.staging"
prod    = "<central-env-dir>/.env.production"

[group.api]
prefix  = "API"
dir     = "./backend"
replace = ["REPLACEABLE1"]
plain   = ["PLAIN1"]
direnv  = ["api"]
check   = true

[group.ui]
prefix  = "UI"
dir     = "./frontend"
replace = ["REPLACEABLE2"]
plain   = ["PLAIN2"]
direnv  = ["ui"]
check   = true
